baseURL = 'https://diligentyield.com/'
languageCode = 'en-us'
title = 'Diligent Yield'


paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-HS91ELQDD3' 
disqusShortname = 'diligentyield-com' # <- Get form here : https://disqus.com

[params]
	
	description = 'At DiligentYield, we deliver timely research and data-driven analysis to help investors uncover market discrepancies and make informed decisions.'
	mainSections = 'posts'
  	logo = "favicon.png"
	defaultAuthor = "Andrei CN"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


[params.authors]
	[[params.authors.author]]
		name = "Andrei CN"
		bio = "Researcher in Behavioral Economics Markets"
		avatar = "/images/author_photo1.jpg"
		twitter = "https://twitter.com/peterfinance"
		linkedin = "https://twitter.com/peterfinance"
		instagram = "https://twitter.com/peterfinance"
		facebook = "https://twitter.com/peterfinance"

	[[params.authors.author]]
	name = "Peter Canariov"
	bio = "Investor. Analyst in Financial Markets"
	avatar = "/images/author_photo2.jpg"
	twitter = "https://twitter.com/peterfinance"
	linkedin = "https://www.linkedin.com/in/petru-canariov-566563176/"
	instagram = "https://twitter.com/peterfinance"
	facebook = "https://twitter.com/peterfinance"

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
		[[menu.main]]
		name = 'Topics'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Undervalued Assets'
		pageRef = '/tags/undervalued/'
		weight = 25
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'