baseURL = 'https://diligentyield.com/'
languageCode = 'en-us'
title = 'Diligent Yield'


paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'

[author]
	name = 'Andrei CN'
	bio = 'Researcher in Behavioral Economics Markets'
	avatar = '/images/author_photo1.png'
	twitter = 'https://twitter.com/insertapps'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
		[[menu.main]]
		name = 'Topics'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Undervalued Assets'
		pageRef = '/tags/undervalued/'
		weight = 25
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'